name: Test action

# This workflow can be triggered manually either through Github UI or through the API
on:
  pull_request:
  workflow_dispatch:

jobs:
  create_eks:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this GHAction
      uses: actions/checkout@v3

    - name: Check out the Reference Architecture V1
      uses: actions/checkout@v3
      with:
        repository: binbashar/le-tf-infra-aws
        path: le-tf-infra-aws
        ref: master

    - name: Configure Reference Architecture V1
      uses: ./
      with:
        dir_name: "le-tf-infra-aws"
        refarch_version: "v1"
        project: "bb"
        project_long: "binbash"
        region_primary: "us-east-1"
        region_secondary: "us-east-2"
        aws_root_account_id: " secrets.AWS_ROOT_ACCOUNT_ID "
        aws_security_account_id: " secrets.AWS_SECURITY_ACCOUNT_ID "
        aws_shared_account_id: " secrets.AWS_SHARED_ACCOUNT_ID "
        aws_devstg_account_id: " secrets.AWS_DEVSTG_ACCOUNT_ID "
        aws_network_account_id: " secrets.AWS_NETWORK_ACCOUNT_ID "
        vault_address: ""
        vault_token: ""
        sso_enabled: false
        sso_start_url: ""
        sso_region: ""


    - name: Check configs V1
      run: |
        echo "############################################"
        echo "# build.env"
        echo "############################################"
        cat build.env
        echo "############################################"
        echo "# common.tfvars"
        echo "############################################"
        cat config/common.tfvars
      working-directory: le-tf-infra-aws

    #- name: Check out the Reference Architecture V2
    #  uses: actions/checkout@v3
    #  with:
    #    repository: binbashar/le-tf-ref-arch-v2-poc
    #    path: le-tf-ref-arch-v2-poc
    #    ref: master

    #- name: Configure Reference Architecture V2
    #  uses: ./
    #  with:
    #    dir_name: "le-tf-ref-arch-v2-poc"
    #    refarch_version: "v2"
    #    project: "bb"
    #    project_long: "binbash"
    #    region_primary: "us-east-1"
    #    region_secondary: "us-east-2"
    #    aws_root_account_id: " secrets.AWS_ROOT_ACCOUNT_ID "
    #    aws_security_account_id: " secrets.AWS_SECURITY_ACCOUNT_ID "
    #    aws_shared_account_id: " secrets.AWS_SHARED_ACCOUNT_ID "
    #    aws_devstg_account_id: " secrets.AWS_DEVSTG_ACCOUNT_ID "
    #    aws_network_account_id: " secrets.AWS_NETWORK_ACCOUNT_ID "
    #    vault_address: ""
    #    vault_token: ""
    #    sso_enabled: false
    #    sso_start_url: ""
    #    sso_region: ""


    #- name: Check configs V2
    #  run: |
    #    echo "############################################"
    #    echo "# build.env"
    #    echo "############################################"
    #    cat build.env
    #    echo "############################################"
    #    echo "# common.tfvars"
    #    echo "############################################"
    #    cat config/common.tfvars
    #  working-directory: le-tf-ref-arch-v2-poc
